shutdown_costmaps: false

controller_frequency: 20.0
controller_patience: 15.0

planner_frequency: 20.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true

# XY goal tolerance (in meters)
xy_goal_tolerance: 0.05

# Yaw goal tolerance (in radians)
yaw_goal_tolerance: 6.28  # 6.28 radians is approximately 360 degrees