# Active localization project 
# specification for the development environment containers
#
# Federico Oliva <federico.oliva.it@gmail.com>
#
# April 3, 2023

# docker compose version
version: "3.9"

# docker compose services. For more information on the detailedoptions please 
# refer to https://docs.docker.com/compose/

services:

  # base setup - noetic
  ros-noetic-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.noetic.x86.base
    image: cearlab/activeloc:ros-noetic-base
    container_name: ros-noetic-base
    tty: true
    working_dir: /home/ros/workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]

  # dev setup - noetic - default
  ros-noetic-dev-activeloc:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.noetic.x86.dev
      args:
        TARGET: dev
    image: cearlab/activeloc:ros-noetic-dev
    container_name: activeloc-dev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
      BOARD: $USER
    privileged: true
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    working_dir: /home/ros/workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
     
      - /sys:/sys - /dev:/dev
      - ~/.Xauthority:/home/ros/.Xauthority:rw
      - ~/.ssh:/home/ros/.ssh
      - ./config/.aliases.sh:/home/ros/.aliases.sh:rw
      - ./config/.p10k.zsh:/home/ros/.p10k.zsh:rw
      - ./config/.zshrc:/home/ros/.zshrc:rw
      - ./config/.bashrc:/home/ros/.bashrc:rw
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ../
        target: /home/ros/workspace

  # dev setup - noetic - nvidia
  ros-noetic-dev-nvidia:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.noetic.x86.dev
      args:
        TARGET: nvidia
    image: cearlab/activeloc:ros-noetic-dev-nvidia
    container_name: aciveloc-nvidia
    runtime: nvidia
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
      BOARD: $USER
    privileged: true
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    working_dir: /home/ros/workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    network_mode: host
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/home/ros/.Xauthority:rw
      - ~/.ssh:/home/ros/.ssh
      - ./config/.aliases.sh:/home/ros/.aliases.sh:rw
      - ./config/.p10k.zsh:/home/ros/.p10k.zsh:rw
      - ./config/.zshrc:/home/ros/.zshrc:rw
      - ./config/.bashrc:/home/ros/.bashrc:rw
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ../
        target: /home/ros/workspace

# define a custom network
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
