shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 5.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 5.0
oscillation_distance: 0.5

# all the following, set them in the launch file

# recovery_behavior_enabled: false
# clearing_rotation_allowed: false

# XY goal tolerance (in meters)
# xy_goal_tolerance: 0.10

# Yaw goal tolerance (in radians)
# yaw_goal_tolerance: 6  # radians