<?xml version="1.0"?>
<robot name="jackal" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Parameters -->
  <xacro:arg name="right_id" default="1" />
  <xacro:arg name="ns" default="" />    

  <xacro:property name="right" value="$(arg right_id)" />       
  <xacro:property name="ns" value="$(arg ns)" />

  <!-- Fixed values -->
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.262" />
  <xacro:property name="track" value="0.37559" />
  <xacro:property name="wheel_vertical_offset" value="0.0345" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />

  <xacro:property name="wheel_radius" value="0.098" />
  <xacro:property name="wheel_width" value="0.040" />

  <xacro:property name="chassis_length" value="0.420" />
  <xacro:property name="chassis_width" value="0.310" />
  <xacro:property name="chassis_height" value="0.184" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <material name="Red">
      <color rgba="${255/255} ${0/255} ${0/255} 1.0"/>
  </material>
  <material name="Green">
      <color rgba="${0/255} ${255/255} ${0/255} 1.0"/>
  </material>   
  <material name="Blue">
      <color rgba="${0/255} ${0/255} ${255/255} 1.0"/>
  </material>   

  <xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://jackal_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <selfCollide>false</selfCollide>
      <mu1 value="1"/>
      <mu2 value="1"/>
      <kp value="10000000.0" />
      <kd value="1" />
      <fdir1 value="1 0 0"/>
    </gazebo>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="$(arg ns)chassis_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <!-- In reality, Jackal has only two motors, one per side. However, it's more
        straightforward for Gazebo to simulate as if there's an actuator per wheel. -->
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:wheel prefix="$(arg ns)front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="$(arg ns)front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="$(arg ns)rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="$(arg ns)rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  
  <link name="$(arg ns)base_link"></link>
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="$(arg ns)base_link"/>
    <child link="$(arg ns)chassis_link" />
  </joint>

  <link name="$(arg ns)chassis_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://jackal_description/meshes/jackal-base.stl"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
      <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
      <mass value="16.523"/>      
      <!-- Moments of inertia: ( chassis without wheels ) -->
      <inertia
        ixx="0.3136" ixy="-0.0008" ixz="0.0164"
        iyy="0.3922" iyz="-0.0009"
        izz="0.4485"/>
      </inertial>
  </link>

  <xacro:unless value="$(optenv JACKAL_FRONT_ACCESSORY_FENDER 0)">
    <link name="$(arg ns)front_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://jackal_description/meshes/jackal-fender.stl"/>
        </geometry>
        <material name="Green" />
      </visual>
    </link>
  </xacro:unless>

  <xacro:if value="$(optenv JACKAL_FRONT_ACCESSORY_FENDER 0)">
    <link name="$(arg ns)front_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://jackal_description/meshes/accessory_fender.stl"/>
        </geometry>
        <material name="Green" />
      </visual>
    </link>

    <link name="$(arg ns)front_fender_accessory_link"/>
    <joint name="front_fender_accessory_joint" type="fixed">
      <origin xyz="0.25629 0 0.07455" rpy="${PI} 0 0" />
      <parent link="$(arg ns)front_fender_link" />
      <child link="$(arg ns)front_fender_accessory_link" />
    </joint>
  </xacro:if>

  <joint name="$(arg ns)front_fender_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="$(arg ns)chassis_link" />
    <child link="$(arg ns)front_fender_link" />
  </joint>

  <xacro:unless value="$(optenv JACKAL_REAR_ACCESSORY_FENDER 0)">
    <link name="$(arg ns)rear_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://jackal_description/meshes/jackal-fender.stl"/>
        </geometry>
        <material name="Red" />
      </visual>
    </link>
  </xacro:unless>

  <xacro:if value="$(optenv JACKAL_REAR_ACCESSORY_FENDER 0)">
    <link name="$(arg ns)rear_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://jackal_description/meshes/accessory_fender.stl"/>
        </geometry>
        <material name="Red" />
      </visual>
    </link>

    <link name="$(arg ns)rear_fender_accessory_link"/>
    <joint name="rear_fender_accessory_joint" type="fixed">
      <origin xyz="0.25629 0 0.07455" rpy="${PI} 0 0" />
      <parent link="$(arg ns)rear_fender_link" />
      <child link="$(arg ns)rear_fender_accessory_link" />
    </joint>
  </xacro:if>

  <joint name="rear_fender_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
    <parent link="$(arg ns)chassis_link" />
    <child link="$(arg ns)rear_fender_link" />
  </joint>

  <!-- IMU LINK -->
  <link name="$(arg ns)imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="$(arg ns)base_link" />
    <child link="$(arg ns)imu_link" />
  </joint>

  <!-- TODO: Same note as applies to imu_link -->
  <link name="$(arg ns)navsat_link">
    <visual>
      <geometry>
        <cylinder radius="0.026" length="0.016" />
      </geometry>
      <origin xyz="0 0 0.008" />
      <material name="black" />
    </visual>
  </link>
  <joint name="navsat_joint" type="fixed">
    <parent link="$(arg ns)chassis_link" />
    <child link="$(arg ns)navsat_link" />
    <origin xyz="-0.180 0.126 0.1815" />
  </joint>

  <link name="$(arg ns)mid_mount"></link>
  <joint name="mid_mount_joint" type="fixed">
    <parent link="$(arg ns)chassis_link" />
    <child link="$(arg ns)mid_mount" />
    <origin xyz="0 0 ${chassis_height}" />
  </joint>

  <link name="$(arg ns)rear_mount"></link>
  <joint name="rear_mount_joint" type="fixed">
    <parent link="$(arg ns)mid_mount" />
    <child link="$(arg ns)rear_mount" />
    <origin xyz="${-mount_spacing} 0 0" />
  </joint>

  <link name="$(arg ns)front_mount"></link>
  <joint name="front_mount_joint" type="fixed">
    <parent link="$(arg ns)mid_mount" />
    <child link="$(arg ns)front_mount" />
    <origin xyz="${mount_spacing} 0 0" />
  </joint>    

  <!-- -->
  <link name="$(arg ns)right_tag">
      <inertial>
          <origin xyz="0 0 0.184" rpy="-1.57 0 -1.57"/>
          <mass value="0.1" />            
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
      </inertial>
      <collision>           
          <origin xyz="0 0 0.184" rpy="-1.57 0 -1.57"/>             
          <geometry>
              <box size="0.05 0.026 0.102"/>
          </geometry>
      </collision>
      <visual>
          <origin xyz="0 0 0.184" rpy="-1.57 0 -1.57"/>
          <geometry>
              <mesh filename="package://jackal_custom/models/DecaWave/meshes/Decawave.stl"/>
          </geometry>
          <material name="Blue"/>
      </visual>
  </link>

  <joint name="right_tag_joint" type="fixed">        
      <parent link="$(arg ns)chassis_link"/>
      <child link="$(arg ns)right_tag"/>
  </joint>  

  <!-- Bring in simulation data for Gazebo. -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">      
    </plugin>
  </gazebo>  

  <gazebo>
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>10.0</updateRate>
          <bodyName>$(arg ns)base_link</bodyName>
          <frameName>world</frameName>
          <topicName>ground_truth/state</topicName>
          <gaussianNoise>0.0</gaussianNoise>          
          <xyzOffsets>0 0 0</xyzOffsets>
          <rpyOffsets>0 0 0</rpyOffsets>
      </plugin>
  </gazebo>

  <gazebo>
    <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">      
      <updateRate>10.0</updateRate>
      <bodyName>$(arg ns)imu_link</bodyName>
      <topicName>imu/data</topicName>
      <accelDrift>0 0 0</accelDrift>
      <accelGaussianNoise>0 0 0</accelGaussianNoise>
      <rateDrift>0 0 0 </rateDrift>
      <rateGaussianNoise>0 0 0 </rateGaussianNoise>
      <headingDrift>0</headingDrift>
      <headingGaussianNoise>0</headingGaussianNoise>
    </plugin>
  </gazebo>
  

  <gazebo reference="$(arg ns)right_tag">
      <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="$(arg ns)base_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo reference="$(arg ns)chassis_link">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  <gazebo reference="$(arg ns)imu_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo reference="$(arg ns)navsat_link">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  <gazebo reference="$(arg ns)front_fender_link">
    <material>Gazebo/Green</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  <gazebo reference="$(arg ns)rear_fender_link">
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  
</robot>
