# Configuration for robot odometry EKF

frequency: 10

# encoders - enabled
odom0_config: [ true, true, true,
                false, false, true,
                true, true, true,
                true, true, true,
                false, false, false]

# encoders - disabled
# odom0_config: [ false, false, false,
#                 false, false, false,
#                 false, false, false,
#                 false, false, false,
#                 false, false, false]
odom0_differential: true

# PF
odom1_config: [ true, true, false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]
odom1_differential: false

# IMU - enabled
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              true, true, true,
              true, true, true]

# IMU - disabled
# imu0_config: [false, false, false,
#               false, false, false,
#               false, false, false,
#               false, false, false,
#               false, false, false,]
imu0_differential: true

predict_to_current_time: true
publish_tf: true
two_d_mode: true
