# Configuration for robot odometry EKF

frequency: 10

odom0_config: [ true, true, true,
                true, true, true,
                false, false, false,
                false, false, false,
                false, false, false]
odom0_differential: false

imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: false

predict_to_current_time: true
publish_tf: true
