# Configuration for robot odometry EKF

frequency: 10

# encoders
odom0_config: [ false, false, false,
                true, true, true,
                true, true, true,
                true, true, true,
                false, false, false]
odom0_differential: false

# PF
odom1_config: [ true, true, true,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]
odom1_differential: false

# IMU
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, false,
              true, true, true]
imu0_differential: true

predict_to_current_time: true
publish_tf: true
two_d_mode: true
